const DISCORD='https://discord.gg/3yWX2qTUZ';
const TIKTOK='https://www.tiktok.com/@nex0ra.gg';
export default function Home(){return <main><div className="noise"/><nav className="nav"><div className="wrap navin"><div className="brand"><img src="/nexora-logo.png" alt="NEXORA logo"/><span>NEXORA</span></div><div className="links"><a href="#community">Community</a><a href="#content">Content</a><a href="#giveaways">Giveaways</a><a href="#partners">Partners</a><a className="btn primary navcta" href={DISCORD}>Join Discord</a></div></div></nav>
<div className="wrap"><header className="hero"><div><span className="eyebrow">Gaming, together.</span><h1>WELCOME TO <span className="gradient">NEXORA.</span></h1><p>A global gaming community built for finding teammates, discovering games, sharing moments and having somewhere to hang out.</p><div className="actions"><a className="btn primary" href={DISCORD}>Join the Discord →</a><a className="btn" href={TIKTOK}>Watch our content</a></div></div><div className="hero-art"><img src="/nox.png" alt="Nox, NEXORA mascot"/></div></header>
<section id="community"><div className="kicker">The community</div><h2 className="section-title">More than another server.</h2><p className="lead">NEXORA is a place to meet people who actually want to play, talk gaming and be part of something that's growing with them.</p><div className="grid3"><article className="card"><span className="num">01</span><h3>Find teammates</h3><p>Stop queueing alone. Meet players, build squads and find people for the games you actually play.</p></article><article className="card"><span className="num">02</span><h3>Hang out</h3><p>No game required. Join the conversation, meet the community and stay for the chaos.</p></article><article className="card"><span className="num">03</span><h3>Discover more</h3><p>Gaming news, recommendations, clips, community events and content worth sending to the group chat.</p></article></div></section>
<section id="content"><div className="kicker">NEXORA content</div><h2 className="section-title">Gaming is the content.</h2><div className="feature"><div className="bigcard"><h3>News without the essay.</h3><p>Fast gaming updates, new releases and stories you may have missed — made for the feed, not a press conference.</p></div><div className="bigcard"><h3>Nox has opinions.</h3><p>Our mascot shows up for recommendations, gaming court, community posts, memes and whatever we decide to put him through next.</p></div></div></section>
<section id="giveaways"><div className="kicker">Giveaways & events</div><h2 className="section-title">Good things happen here.</h2><p className="lead">Game giveaways, community milestones and events live inside NEXORA. Join the Discord and follow our socials so you don't miss the next one.</p><div className="actions"><a className="btn primary" href={DISCORD}>Enter through Discord →</a><a className="btn" href={TIKTOK}>Follow @nex0ra.gg</a></div></section>
<section id="partners"><div className="kicker">Partners</div><h2 className="section-title">Brands we work with.</h2><div className="partner"><div><div className="kicker">NEXORA × DUBBY</div><h3 style={{fontSize:'32px',margin:'10px 0'}}>Fuel the next session.</h3><p className="lead" style={{fontSize:'16px'}}>Use our community code at DUBBY and support NEXORA at the same time.</p></div><div><div className="code">NEXORADUBBY</div><div style={{color:'#aaa5b2',marginTop:'7px'}}>10% off</div></div></div></section>
<section><div className="kicker">Meet Nox</div><h2 className="section-title">Yeah. He's staying.</h2><p className="lead">Nox is the face of NEXORA: unimpressed, occasionally helpful and somehow always involved.</p></section>
</div><footer className="footer"><div className="wrap"><div className="footerrow"><div className="brand"><img src="/nexora-logo.png" alt=""/><span>NEXORA</span></div><div className="socials"><a href={DISCORD}>Discord</a><a href={TIKTOK}>TikTok</a><a href="#">Instagram</a><a href="#">YouTube</a><a href="#">Twitch</a></div></div><div className="tiny">© 2026 NEXORA. Built for gamers, wherever they are.</div></div></footer></main>}
