import Experience from './Experience'
const DISCORD='https://discord.gg/3yWX2qTUZ';
const TIKTOK='https://www.tiktok.com/@nex0ra.gg';
const DUBBY='https://www.dubby.gg/';
const pillars=[['01','SQUAD UP','Find players who actually play what you play. Build a squad, queue up and stop gaming alone.'],['02','LIVE THE COMMUNITY','Clips, voice chats, events, chaos and people worth coming back for.'],['03','STAY IN THE LOOP','Gaming news, recommendations, giveaways and content without the filler.']];
const newsItems=[
 {category:'TECH',title:'APPLE PREPARING FIX FOR IPHONE 18 PRO FACE ID RESTART BUG',summary:'Some iPhone 18 Pro models can freeze and reboot after failed Face ID authentication. Apple says a software fix is coming.',date:'SEP 25, 2026',link:'/news/iphone-18-pro-face-id-restart-fix'},
 {category:'TECH NEWS',title:'TECH NEWS',summary:'PC hardware, consoles, gaming technology and industry updates — focused on the things that actually matter to players.',date:'TECHWIRE',link:TIKTOK},
 {category:'NEXORA',title:'MORE STORIES COMING',summary:'This section is updated as we cover new stories. Follow NEXORA on TikTok for our latest gaming and tech posts.',date:'UPDATING',link:TIKTOK}
];
const giveaways=[
 {title:'HUMAN FALL FLAT',prize:'2 GAME KEYS • 2 WINNERS',status:'ACTIVE',description:'Our current NEXORA giveaway has two Human Fall Flat game keys up for grabs, with two separate winners. Join the Discord to be part of the community and open our TikTok for the giveaway post and entry information.'},
 {title:'BATMAN: ARKHAM COLLECTION',prize:'PREVIOUS NEXORA GIVEAWAY',status:'ENDED',description:'This NEXORA giveaway has officially ended. It remains here in our giveaway archive as part of the community’s history — thank you to everyone who entered.'}
];
export default function Home(){return <main id="top"><Experience/>
<div className="cursorGlow"/><div className="mesh"/><div className="scanlines"/>
<nav className="nav"><div className="wrap navin"><a href="#top" className="brand"><img src="/nexora-logo.png" alt="NEXORA"/><span>NEXORA</span></a><div className="navlinks"><a href="#community">COMMUNITY</a><a href="#news">NEWS</a><a href="#content">CONTENT</a><a href="#giveaways">DROPS</a><a href="#partners">PARTNERS</a></div><a className="navjoin" href={DISCORD} target="_blank" rel="noreferrer"><i/> JOIN NEXORA</a></div></nav>

<header className="hero wrap">
<div className="heroCopy"><div className="micro"><span>A GLOBAL GAMING COMMUNITY</span><b>● ONLINE</b></div><h1><em>THIS IS WHERE</em><br/><span>GAMERS</span><br/>CONNECT.</h1><p>Find teammates. Stay updated. Join giveaways.<br/>Or just hang out — you’re always welcome here.</p><div className="heroActions"><a className="cta" href={DISCORD} target="_blank" rel="noreferrer">JOIN OUR SERVER <span>→</span></a><a className="conceptTikTok" href={TIKTOK} target="_blank" rel="noreferrer">♪ &nbsp; FOLLOW ON TIKTOK <span>→</span></a></div><div className="heroProof"><span>♟ Active Community</span><span>♪ Regular Giveaways</span><span>▣ Gaming News</span><span>✦ Everyone’s Welcome</span></div></div>
<div className="heroVisual conceptHero"><div className="rings"><i/><i/><i/></div><div className="purpleCore"/><div className="welcomeBubble">HEY!<br/><b>WELCOME TO<br/>NEXORA!</b><i>↘</i></div><div className="conceptTags"><span>FIND TEAMMATES</span><span>GAMING NEWS</span><span>GIVEAWAYS</span><span>HANG OUT</span></div><img src="/nox.png" alt="Nox"/><div className="noxName">NOX<span>01</span></div></div>
<div className="scroll">SCROLL TO ENTER <i/></div></header>

<div className="ticker"><div>FIND TEAMMATES <b>✦</b> GAMING NEWS <b>✦</b> GIVEAWAYS <b>✦</b> COMMUNITY EVENTS <b>✦</b> MEMES <b>✦</b> GAME RECOMMENDATIONS <b>✦</b> FIND TEAMMATES <b>✦</b> GAMING NEWS <b>✦</b> GIVEAWAYS <b>✦</b> COMMUNITY EVENTS <b>✦</b></div></div>

<section id="community" className="wrap community"><div className="sectionNum">01</div><div className="sectionIntro"><div className="eyebrow">THE COMMUNITY</div><h2>NOT JUST A<br/><span>SERVER.</span></h2><p>NEXORA is the place between the games — where the squad forms, the clips get shared and the next session starts.</p></div><div className="pillarGrid">{pillars.map(([n,t,d])=><article className="pillar" key={n}><div className="pnum">{n}</div><div className="corner">↗</div><div className="pIcon">{n==='01'?'⌁':n==='02'?'◉':'⌾'}</div><h3>{t}</h3><p>{d}</p><div className="line"/></article>)}</div></section>

<section id="news" className="newsroom"><div className="wrap"><div className="sectionNum">02</div><div className="splitTitle"><div><div className="eyebrow">NEXORA // NEWSWIRE</div><h2>GAMING + TECH.<br/><span>IN THE LOOP.</span></h2></div><p className="newsLead">A living feed for the stories worth knowing. New posts can be added here whenever they drop.</p></div><div className="newsGrid">{newsItems.map((item,i)=><a className={"newsCard "+(i===0?'featuredNews':'')} href={item.link} target={item.link.startsWith('http')?'_blank':undefined} rel={item.link.startsWith('http')?'noreferrer':undefined} key={item.title}><div className="newsMeta"><span>{item.category}</span><b>{item.date}</b></div><div className="newsIndex">0{i+1}</div><h3>{item.title}</h3><p>{item.summary}</p><div className="readMore">READ ARTICLE <span>→</span></div></a>)}</div></div></section><section id="content" className="contentSection"><div className="wrap"><div className="sectionNum">03</div><div className="splitTitle"><div><div className="eyebrow">NEXORA ON YOUR FEED</div><h2>CONTENT THAT<br/><span>HITS DIFFERENT.</span></h2></div><a href={TIKTOK} target="_blank" rel="noreferrer">VIEW @NEX0RA.GG ↗</a></div><div className="showcase"><article className="show mainShow"><div className="hud">NXR // NEWS_001</div><div className="crosshair">+</div><div className="showCopy"><small>FAST. CLEAN. WORTH KNOWING.</small><h3>GAMING NEWS<br/>WITHOUT THE<br/>PRESS CONFERENCE.</h3><p>The stories you care about, made for the feed.</p></div></article><article className="show noxShow"><img src="/nox.png" alt="Nox"/><div className="hud">NXR // NOX_001</div><div className="showCopy"><small>OUR RESIDENT MENACE</small><h3>NOX HAS<br/>OPINIONS.</h3><p>Gaming Court. Reviews. Memes. Questionable decisions.</p></div></article></div></div></section>

<section id="giveaways" className="wrap drop"><div className="sectionNum">04</div><div className="dropHeader"><div><div className="eyebrow">DROPS / GIVEAWAYS / EVENTS</div><h2>WIN SOMETHING.<br/><span>STAY FOR MORE.</span></h2></div><p>Every giveaway has a clear status and its own details. Active drops include direct links to our Discord and TikTok; completed giveaways stay here in the NEXORA archive.</p></div><div className="giveawayGrid">{giveaways.map((g,i)=>{const active=g.status==='ACTIVE';return (<article className={"giveawayCard "+(active?'isActive':'isEnded')} key={g.title}><div className="giveStatus"><i/>{g.status}</div><div className="giveNum">DROP // 0{i+1}</div><div className="giveBody"><small>{g.prize}</small><h3>{g.title}</h3><p>{g.description}</p></div>{active?<div className="giveActions"><a href={DISCORD} target="_blank" rel="noreferrer">JOIN DISCORD ↗</a><a href={TIKTOK} target="_blank" rel="noreferrer">VIEW TIKTOK ↗</a></div>:<div className="endedStamp">ARCHIVED // ENDED</div>}</article>)})}</div></section><section id="partners" className="partnerSection"><div className="wrap"><div className="sectionNum">05</div><div className="eyebrow">OFFICIAL PARTNER</div><div className="partnerHero"><div><h2>NEXORA <span>×</span><br/>DUBBY.</h2><p>Fuel the next session and support the community. Use our code at checkout.</p><a href={DUBBY} target="_blank" rel="noreferrer">VISIT DUBBY ↗</a></div><div className="codeBox"><small>COMMUNITY CODE</small><strong>NEXORADUBBY</strong><div><span>10%</span> OFF YOUR ORDER</div></div></div></div></section>

<section className="end wrap"><div className="endLogo"><img src="/nexora-logo.png" alt="NEXORA"/><div className="pulse"/></div><div className="eyebrow">THE LOBBY IS OPEN</div><h2>YOUR SQUAD<br/>COULD BE<br/><span>WAITING.</span></h2><p>Join NEXORA. Say hi. Find a game. Stay awhile.</p><a className="cta mega" href={DISCORD} target="_blank" rel="noreferrer">JOIN THE COMMUNITY <span>↗</span></a></section>

<footer><div className="wrap foot"><a className="brand" href="#top"><img src="/nexora-logo.png" alt=""/><span>NEXORA</span></a><div className="footlinks"><a href={DISCORD} target="_blank" rel="noreferrer">DISCORD ↗</a><a href={TIKTOK} target="_blank" rel="noreferrer">TIKTOK ↗</a></div><div className="copy">© 2026 // NEXORA<br/>GAMING, TOGETHER.</div></div></footer>
</main>}