import Experience from './Experience'
import SiteExtras from './SiteExtras'
import GiveawayCountdown from './GiveawayCountdown'
import LiveStats from './LiveStats'
import StatusPanel from './StatusPanel'
import ExploreSection from './ExploreSection'
import ReleaseCalendar from './releases/ReleaseCalendar'
import './releases/releases.css'
import './home-releases.css'
import NewsletterSection from './NewsletterSection'
const DISCORD='https://discord.gg/3yWX2qTUZ';
const TIKTOK='https://www.tiktok.com/@nex0ra.gg';
const DUBBY='https://www.dubby.gg/';
const pillars=[['01','SQUAD UP','Find players who actually play what you play. Build a squad, queue up and stop gaming alone.'],['02','LIVE THE COMMUNITY','Clips, voice chats, events, chaos and people worth coming back for.'],['03','STAY IN THE LOOP','Gaming news, recommendations, giveaways and content without the filler.']];
const newsItems=[{category:'TECH',title:'MODDERS BRING NVIDIA SMOOTH MOTION TO RTX 30-SERIES GPUs',summary:'Unofficial community tools are enabling NVIDIA’s driver-level Smooth Motion frame interpolation on RTX 30-series Ampere hardware.',date:'SEP 24, 2026',link:'/news/rtx-30-smooth-motion-mod',image:'https://cdn.tgdd.vn/Files/2015/01/05/596153/card-do-hoa-la-gi--5.jpg'},
 {category:'TECH',title:'APPLE PREPARING FIX FOR IPHONE 18 PRO FACE ID RESTART BUG',summary:'Some iPhone 18 Pro models can freeze and reboot after failed Face ID authentication. Apple says a software fix is coming.',date:'SEP 25, 2026',link:'/news/iphone-18-pro-face-id-restart-fix',image:'https://www.apple.com/newsroom/images/2026/09/apple-debuts-iphone-18-pro-and-iphone-18-pro-max/article/Apple-iPhone-18-Pro-2up-260909_inline.jpg.large.jpg'},
 {category:'GAMING',title:'PERSONA 3 RELOAD MITSURU KIRIJO FIGURE REVEALED',summary:'AMAKUNI has unveiled a new 1/7-scale Mitsuru Kirijo figure, with its Japanese release planned for 2027 and an October 2027 US retailer estimate.',date:'SEP 27, 2026',link:'/news/persona-3-reload-mitsuru-figure',image:'https://www.inside-games.jp/imgs/zoom/1282992.png'},
 {category:'GAMING',title:'HYTALE PUTS $15,000 ON THE GOBLITERATOR BOSS CHALLENGE',summary:'The first streamer to defeat Hytale’s upcoming Gobliterator under a brutal hardcore ruleset can claim a $15,000 reward.',date:'SEP 28, 2026',link:'/news/hytale-15000-gobliterator-challenge',image:'https://cdn.mos.cms.futurecdn.net/v2/t%3A0%2Cl%3A480%2Ccw%3A1600%2Cch%3A1600%2Cq%3A80%2Cw%3A1600/NnriYkjFFhBaQXuRxnDh6W.jpg'}
];
const giveaways=[
 {title:'HUMAN FALL FLAT',prize:'2 GAME KEYS • 2 WINNERS',status:'ACTIVE',description:'Our current NEXORA giveaway has two Human Fall Flat game keys up for grabs, with two separate winners. Join the Discord to be part of the community and open our TikTok for the giveaway post and entry information.'},
 {title:'BATMAN: ARKHAM COLLECTION',prize:'PREVIOUS NEXORA GIVEAWAY',status:'ENDED',description:'This NEXORA giveaway has officially ended. It remains here in our giveaway archive as part of the community’s history — thank you to everyone who entered.'}
];
export default function Home(){return <main id="top"><Experience/><SiteExtras/>
<div className="cursorGlow"/><div className="mesh"/><div className="scanlines"/>
<nav className="nav"><div className="wrap navin"><a href="#top" className="brand"><img src="/nexora-logo.png" alt="NEXORA"/><span>NEXORA</span></a><div className="navlinks"><a href="#community">COMMUNITY</a><a href="#news">NEWS</a><a href="#content">CONTENT</a><a href="#giveaways">DROPS</a><a href="#partners">PARTNERS</a><a href="#newsletter">UPDATES</a></div><a className="navjoin" href={DISCORD} target="_blank" rel="noreferrer"><i/> JOIN NEXORA</a></div></nav>
<header className="hero wrap"><div className="heroCopy"><div className="micro"><span>A GLOBAL GAMING COMMUNITY</span><b>● ONLINE</b></div><h1><em>THIS IS WHERE</em><br/><span>GAMERS</span><br/>CONNECT.</h1><p>Find teammates. Stay updated. Join giveaways.<br/>Or just hang out — you’re always welcome here.</p><div className="heroActions"><a className="cta" href={DISCORD} target="_blank" rel="noreferrer">JOIN OUR SERVER <span>→</span></a><a className="conceptTikTok" href={TIKTOK} target="_blank" rel="noreferrer">♪ &nbsp; FOLLOW ON TIKTOK <span>→</span></a></div><button className="copyInvite" data-copy-discord="true">COPY INVITE ⧉</button><div className="heroProof"><span>♟ Active Community</span><span>♪ Regular Giveaways</span><span>▣ Gaming News</span><span>✦ Everyone’s Welcome</span></div></div><div className="heroVisual conceptHero"><div className="rings"><i/><i/><i/></div><div className="purpleCore"/><div className="welcomeBubble">HEY!<br/><b>WELCOME TO<br/>NEXORA!</b><i>↘</i></div><div className="conceptTags"><span>FIND TEAMMATES</span><span>GAMING NEWS</span><span>GIVEAWAYS</span><span>HANG OUT</span></div><img src="/nox.png" alt="Nox"/><div className="noxName">NOX<span>01</span></div></div><div className="scroll">SCROLL TO ENTER <i/></div></header><LiveStats/>
<div className="ticker"><div>FIND TEAMMATES <b>✦</b> GAMING NEWS <b>✦</b> GIVEAWAYS <b>✦</b> COMMUNITY EVENTS <b>✦</b> MEMES <b>✦</b> GAME RECOMMENDATIONS <b>✦</b> FIND TEAMMATES <b>✦</b> GAMING NEWS <b>✦</b> GIVEAWAYS <b>✦</b> COMMUNITY EVENTS <b>✦</b></div></div>
<section id="community" className="wrap community"><div className="sectionIntro"><div className="sectionLabel"><div className="sectionNum">1</div><div className="eyebrow">THE COMMUNITY</div></div><h2>NOT JUST A<br/><span>SERVER.</span></h2><p>NEXORA is the place between the games — where the squad forms, the clips get shared and the next session starts.</p></div><div className="pillarGrid">{pillars.map(([n,t,d])=><article className="pillar" key={n}><div className="pnum">{n}</div><div className="corner">↗</div><div className="pIcon">{n==='01'?'⌁':n==='02'?'◉':'⌾'}</div><h3>{t}</h3><p>{d}</p><div className="line"/></article>)}</div></section>
<section id="news" className="newsroom"><div className="wrap"><div className="splitTitle numberedTitle"><div><div className="sectionLabel"><div className="sectionNum">2</div><div className="eyebrow">NEXORA // NEWSWIRE</div></div><h2>GAMING + TECH.<br/><span>IN THE LOOP.</span></h2></div><p className="newsLead">A living feed for the stories worth knowing. New posts can be added here whenever they drop.</p></div><div className="newsGrid">{newsItems.map((item,i)=><a className={"newsCard "+(i===0?'featuredNews':'')} href={item.link} target={item.link.startsWith('http')?'_blank':undefined} rel={item.link.startsWith('http')?'noreferrer':undefined} key={item.title}>{item.image&&<div className="newsCover"><img src={item.image} alt={item.title}/></div>}<div className="newsMeta"><span>{item.category}</span><b>{item.date}</b></div><div className="newsIndex">0{i+1}</div><h3>{item.title}</h3><p>{item.summary}</p><div className="readMore">READ ARTICLE <span>→</span></div></a>)}</div><a className="sectionPortal" href="/news">EXPLORE ALL NEXORA NEWS <span>→</span></a><section id="releases" className="homeReleaseBlock" aria-labelledby="homeReleaseTitle"><div className="homeReleaseHead"><div><small>NEXORA // RELEASE CALENDAR</small><h3 id="homeReleaseTitle">UPCOMING <span>GAMES.</span></h3><p>Browse release dates by month and platform. Dates may change.</p></div><a href="/releases">FULL CALENDAR ↗</a></div><ReleaseCalendar compact /></section></div></section>
<section id="content" className="contentSection"><div className="wrap"><div className="splitTitle numberedTitle"><div><div className="sectionLabel"><div className="sectionNum">3</div><div className="eyebrow">NEXORA ON YOUR FEED</div></div><h2>CONTENT THAT<br/><span>HITS DIFFERENT.</span></h2></div><a href={TIKTOK} target="_blank" rel="noreferrer">VIEW @NEX0RA.GG ↗</a></div><div className="showcase"><article className="show mainShow"><div className="hud">NXR // NEWS_001</div><div className="crosshair">+</div><div className="showCopy"><small>FAST. CLEAN. WORTH KNOWING.</small><h3>GAMING NEWS<br/>WITHOUT THE<br/>PRESS CONFERENCE.</h3><p>The stories you care about, made for the feed.</p></div></article><article className="show noxShow"><img className="sectionNox noxThinking" src="/nox/nox-thinking.webp" alt="Nox thinking"/><div className="hud">NXR // NOX_001</div><div className="showCopy"><small>OUR RESIDENT MENACE</small><h3>NOX HAS<br/>OPINIONS.</h3><p>Gaming Court. Reviews. Memes. Questionable decisions.</p></div></article></div><section className="noxIntro"><img className="sectionNox noxHappy" src="/nox/nox-happy.webp" alt="Nox happy"/><div><small>NXR // MASCOT_001</small><h3>MEET NOX.</h3><p>NEXORA's resident menace. He shows up for the news, the memes, the questionable gaming takes and apparently this website too.</p></div></section></div></section>
<StatusPanel/><section className="activityTerminal wrap"><div><small>COMMUNITY SYSTEM</small><strong>NEXORA ONLINE</strong></div><span>NEWSWIRE UPDATED</span><span>GIVEAWAY HUB ACTIVE</span><span>DISCORD LINK READY</span></section><section className="lfgSection wrap"><div className="eyebrow">SQUAD FINDER // LFG</div><h2>WHAT ARE YOU<br/><span>PLAYING?</span></h2><p>Pick a lane. Jump into NEXORA and find people to queue with.</p><div className="gameChips"><a href={DISCORD} target="_blank" rel="noreferrer">LEAGUE OF LEGENDS <span>↗</span></a><a href={DISCORD} target="_blank" rel="noreferrer">VALORANT <span>↗</span></a><a href={DISCORD} target="_blank" rel="noreferrer">MINECRAFT <span>↗</span></a><a href={DISCORD} target="_blank" rel="noreferrer">FORTNITE <span>↗</span></a><a href={DISCORD} target="_blank" rel="noreferrer">OTHER GAMES <span>↗</span></a></div></section>
<section id="giveaways" className="wrap drop"><div className="dropHeader numberedTitle"><div><div className="sectionLabel"><div className="sectionNum">4</div><div className="eyebrow">DROPS / GIVEAWAYS / EVENTS</div></div><h2>WIN SOMETHING.<br/><span>STAY FOR MORE.</span></h2></div><p>Every giveaway has a clear status and its own details. Active drops include direct links to our Discord and TikTok; completed giveaways stay here in the NEXORA archive.</p></div><div className="giveTimeline"><i/><span>ACTIVE DROP</span><span>ARCHIVE</span><b>NEXORA GIVEAWAY HISTORY</b></div><div className="giveawayGrid">{giveaways.map((g,i)=>{const active=g.status==='ACTIVE';return (<article className={"giveawayCard "+(active?'isActive':'isEnded')} key={g.title}><div className="giveStatus"><i/>{g.status}</div><div className="giveNum">DROP // 0{i+1}</div><div className="giveBody">{active&&<GiveawayCountdown/>}<small>{g.prize}</small><h3>{g.title}</h3><p>{g.description}</p></div>{active?<div className="giveActions"><a href={DISCORD} target="_blank" rel="noreferrer">JOIN DISCORD ↗</a><a href={TIKTOK} target="_blank" rel="noreferrer">VIEW TIKTOK ↗</a></div>:<div className="endedStamp">ARCHIVED // ENDED</div>}</article>)})}</div><a className="sectionPortal" href="/giveaways">OPEN GIVEAWAY HUB <span>→</span></a></section>
<section id="partners" className="partnerSection"><div className="wrap"><div className="sectionLabel"><div className="sectionNum">5</div><div className="eyebrow">OFFICIAL PARTNER</div></div><div className="partnerHero"><div><h2>NEXORA <span>×</span><br/>DUBBY.</h2><p>Fuel the next session and support the community. Use our code at checkout.</p><a href={DUBBY} target="_blank" rel="noreferrer">VISIT DUBBY ↗</a></div><div className="codeBox"><small>COMMUNITY CODE</small><strong>NEXORADUBBY</strong><div><span>10%</span> OFF YOUR ORDER</div></div></div></div></section>
<ExploreSection/>
<NewsletterSection/>
<section className="end wrap"><div className="endLogo"><img src="/nexora-logo.png" alt="NEXORA"/><div className="pulse"/></div><div className="eyebrow">THE LOBBY IS OPEN</div><h2>YOUR SQUAD<br/>COULD BE<br/><span>WAITING.</span></h2><p>Join NEXORA. Say hi. Find a game. Stay awhile.</p><a className="cta mega" href={DISCORD} target="_blank" rel="noreferrer">JOIN THE COMMUNITY <span>↗</span></a></section>
<footer><div className="footerTop wrap"><div><div className="eyebrow">NEXORA // END OF LINE</div><h3>GAME TOGETHER.<br/><span>STAY CONNECTED.</span></h3></div><div className="footerNav"><a href="/news">NEWS</a><a href="/giveaways">GIVEAWAYS</a><a href="#community">COMMUNITY</a><a href="#partners">PARTNERS</a><a href="#newsletter">NEWSLETTER</a></div></div><div className="wrap foot"><a className="brand" href="#top"><img src="/nexora-logo.png" alt=""/><span>NEXORA</span></a><div className="footlinks"><a href={DISCORD} target="_blank" rel="noreferrer">DISCORD ↗</a><a href={TIKTOK} target="_blank" rel="noreferrer">TIKTOK ↗</a></div><div className="copy">© 2026 // NEXORA<br/>GAMING, TOGETHER.</div></div></footer>
<div className="legalLinks"><span>© 2026 NEXORA</span><a href="/terms">TERMS</a><a href="/privacy">PRIVACY</a></div></main>}
