'use client'
import {useEffect,useState} from 'react'
const DISCORD='https://discord.gg/3yWX2qTUZ'
export default function SiteSystems(){
 const[cmd,setCmd]=useState(false),[menu,setMenu]=useState(false),[toast,setToast]=useState(''),[achievement,setAchievement]=useState('')
 useEffect(()=>{const key=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setCmd(v=>!v)}if(e.key==='Escape'){setCmd(false);setMenu(false)}};const vis=()=>{document.title=document.hidden?'NOX IS WAITING...':'NEXORA — Gaming, Together.'};const scroll=()=>{if(scrollY/(document.documentElement.scrollHeight-innerHeight||1)>.94&&!sessionStorage.getItem('nxr-scroll')){sessionStorage.setItem('nxr-scroll','1');setAchievement('ACHIEVEMENT // END OF THE LOBBY');setTimeout(()=>setAchievement(''),3200)}};addEventListener('keydown',key);document.addEventListener('visibilitychange',vis);addEventListener('scroll',scroll,{passive:true});return()=>{removeEventListener('keydown',key);document.removeEventListener('visibilitychange',vis);removeEventListener('scroll',scroll)}},[])
 const copy=async()=>{await navigator.clipboard.writeText(DISCORD);setToast('DISCORD INVITE COPIED');setTimeout(()=>setToast(''),1800)}
 const go=h=>{setCmd(false);setMenu(false);if(h.startsWith('#'))document.querySelector(h)?.scrollIntoView({behavior:'smooth'});else location.href=h}
 return <><button className="mobileMenuBtn" onClick={()=>setMenu(v=>!v)} aria-label="Open navigation">☰</button>{menu&&<div className="mobileMenu"><button onClick={()=>setMenu(false)}>×</button><a href="#community">COMMUNITY</a><a href="/news">NEWS</a><a href="#content">CONTENT</a><a href="/giveaways">GIVEAWAYS</a><a href="#partners">PARTNERS</a><button onClick={copy}>COPY DISCORD INVITE</button></div>}
 <button className="commandHint" onClick={()=>setCmd(true)}>CTRL K <span>COMMAND</span></button>{cmd&&<div className="commandShade" onClick={()=>setCmd(false)}><div className="commandBox" onClick={e=>e.stopPropagation()}><small>NEXORA // QUICK ACCESS</small><strong>WHERE TO?</strong>{[['COMMUNITY','#community'],['NEWSWIRE','/news'],['CONTENT','#content'],['GIVEAWAYS','/giveaways'],['PARTNERS','#partners']].map(x=><button key={x[0]} onClick={()=>go(x[1])}><span>{x[0]}</span>↗</button>)}<button onClick={copy}><span>COPY DISCORD INVITE</span>⌘</button></div></div>}
 <button className="backTop" onClick={()=>scrollTo({top:0,behavior:'smooth'})} aria-label="Back to top">↑</button>{toast&&<div className="siteToast">{toast}</div>}{achievement&&<div className="achievement">{achievement}<small>YOU SCROLLED THE WHOLE SITE</small></div>}</>
}