'use client'
import {useEffect,useState} from 'react'
const DISCORD='https://discord.gg/3yWX2qTUZ'
const ACH={first:['FIRST CONTACT','Entered NEXORA'],scroll:['END OF THE LOBBY','Reached the bottom'],nox:['FOUND NOX','Found the hidden mascot'],konami:['OLD SCHOOL','Entered the classic code'],reader:['NEWS ADDICT','Opened three NEXORA stories']}
function profile(){try{return JSON.parse(localStorage.getItem('nxr-profile'))||{xp:0,ach:[],reads:[]}}catch{return{xp:0,ach:[],reads:[]}}}
export default function SiteSystems(){const[cmd,setCmd]=useState(false),[menu,setMenu]=useState(false),[toast,setToast]=useState(''),[p,setP]=useState({xp:0,ach:[],reads:[]}),[enc,setEnc]=useState(false)
 const save=n=>{localStorage.setItem('nxr-profile',JSON.stringify(n));setP(n)}
 const unlock=(id,xp=25)=>{const cur=profile();if(cur.ach.includes(id))return;const n={...cur,xp:cur.xp+xp,ach:[...cur.ach,id]};save(n);setToast('ACHIEVEMENT // '+ACH[id][0]+'  +'+xp+' XP');setTimeout(()=>setToast(''),2600)}
 useEffect(()=>{let seq=[];let cur=profile();setP(cur);if(!cur.ach.includes('first'))setTimeout(()=>unlock('first',10),900);if(location.pathname.startsWith('/news/')&&!location.pathname.endsWith('/news')){const reads=[...new Set([...cur.reads,location.pathname])];cur={...cur,reads};localStorage.setItem('nxr-profile',JSON.stringify(cur));setP(cur);if(reads.length>=3)setTimeout(()=>unlock('reader',40),1200)}
 const key=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setCmd(v=>!v)}if(e.key==='Escape'){setCmd(false);setMenu(false)}seq=[...seq,e.key.toLowerCase()].slice(-10);if(seq.join(',')==='arrowup,arrowup,arrowdown,arrowdown,arrowleft,arrowright,arrowleft,arrowright,b,a'){document.body.classList.add('konami');unlock('konami',50);setTimeout(()=>document.body.classList.remove('konami'),4200)}};
 const vis=()=>{document.title=document.hidden?'NOX IS WAITING...':'NEXORA — Gaming, Together.'};const scroll=()=>{if(scrollY/(document.documentElement.scrollHeight-innerHeight||1)>.94)unlock('scroll',25)};const click=e=>{if(e.target.closest('[data-copy-discord]'))copy()};addEventListener('keydown',key);document.addEventListener('visibilitychange',vis);addEventListener('scroll',scroll,{passive:true});document.addEventListener('click',click);const encounter=setTimeout(()=>setEnc(true),18000);return()=>{clearTimeout(encounter);removeEventListener('keydown',key);document.removeEventListener('visibilitychange',vis);removeEventListener('scroll',scroll);document.removeEventListener('click',click)}},[])
 const copy=async()=>{await navigator.clipboard.writeText(DISCORD);setToast('DISCORD INVITE COPIED');setTimeout(()=>setToast(''),1800)};const go=h=>{setCmd(false);setMenu(false);if(h.startsWith('#'))document.querySelector(h)?.scrollIntoView({behavior:'smooth'});else location.href=h};const level=Math.floor(p.xp/100)+1,progress=p.xp%100
 return <><div className="playerHud"><small>PLAYER LVL {String(level).padStart(2,'0')}</small><b>{p.xp} XP</b><i><em style={{width:progress+'%'}}/></i><a href="/achievements">ACHIEVEMENTS</a></div><nav className="miniMap" aria-label="Page sections">{[['01','#community'],['02','#news'],['03','#content'],['04','#giveaways'],['05','#partners']].map(x=><a href={x[1]} key={x[0]}>{x[0]}</a>)}</nav>
 <button className="mobileMenuBtn" onClick={()=>setMenu(v=>!v)} aria-label="Open navigation">☰</button>{menu&&<div className="mobileMenu"><button onClick={()=>setMenu(false)}>×</button><a href="/#community">COMMUNITY</a><a href="/news">NEWS</a><a href="/#content">CONTENT</a><a href="/giveaways">GIVEAWAYS</a><a href="/achievements">ACHIEVEMENTS</a><a href="/changelog">CHANGELOG</a><button onClick={copy}>COPY DISCORD INVITE</button></div>}
 <button className="commandHint" onClick={()=>setCmd(true)}>CTRL K <span>COMMAND</span></button>{cmd&&<div className="commandShade" onClick={()=>setCmd(false)}><div className="commandBox" onClick={e=>e.stopPropagation()}><small>NEXORA // QUICK ACCESS</small><strong>WHERE TO?</strong>{[['COMMUNITY','/#community'],['NEWSWIRE','/news'],['DROPS','/giveaways'],['ACHIEVEMENTS','/achievements'],['NOX ROOM','/nox'],['CHANGELOG','/changelog']].map(x=><button key={x[0]} onClick={()=>go(x[1])}><span>{x[0]}</span>↗</button>)}<button onClick={copy}><span>COPY DISCORD INVITE</span>⌘</button></div></div>}
 {enc&&<button className="noxEncounter" onClick={()=>{unlock('nox',35);location.href='/nox'}}><img src="/nox/nox-happy.webp" alt="Nox"/><span>NOX FOUND YOU.<b>CLICK ME →</b></span></button>}<button className="backTop" onClick={()=>scrollTo({top:0,behavior:'smooth'})} aria-label="Back to top">↑</button>{toast&&<div className="siteToast">{toast}</div>}</>}
